# Generated by Django 2.0.5 on 2020-04-29 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardmoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(default='', max_length=32)),
                ('rest_money', models.CharField(default='', max_length=32)),
                ('consume_money', models.CharField(default='', max_length=32)),
                ('consume_time', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(default='', max_length=32)),
            ],
            options={
                'verbose_name': '消费表',
                'verbose_name_plural': '消费表',
                'db_table': 'userconsume',
                'ordering': ['-consume_time'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('card', models.CharField(default='', max_length=20)),
                ('name', models.CharField(default='', max_length=20)),
                ('onlyid', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'userlogin',
                'ordering': ['-c_time'],
            },
        ),
        migrations.AddField(
            model_name='cardmoney',
            name='cardnum',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='card.User'),
        ),
    ]
