# Generated by Django 2.0.5 on 2020-05-06 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmoney',
            name='card',
            field=models.CharField(default='', max_length=32, verbose_name='卡号'),
        ),
        migrations.AlterField(
            model_name='cardmoney',
            name='cardnum',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='card.User', verbose_name='外键'),
        ),
        migrations.AlterField(
            model_name='cardmoney',
            name='consume_money',
            field=models.CharField(max_length=32, verbose_name='消费金额'),
        ),
        migrations.AlterField(
            model_name='cardmoney',
            name='consume_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='消费时间'),
        ),
        migrations.AlterField(
            model_name='cardmoney',
            name='rest_money',
            field=models.CharField(max_length=32, verbose_name='剩余金额'),
        ),
        migrations.AlterField(
            model_name='cardmoney',
            name='username',
            field=models.CharField(default='', max_length=32, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='card',
            field=models.CharField(default='', max_length=20, verbose_name='卡号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='onlyid',
            field=models.CharField(default='', max_length=50, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=128, unique=True, verbose_name='用户名'),
        ),
    ]
