# Generated by Django 2.0.5 on 2020-04-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_auto_20200412_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onlyid',
            field=models.CharField(default='', max_length=50),
        ),
    ]
