# Generated by Django 2.0.5 on 2020-05-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_auto_20200506_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(default='', max_length=32, verbose_name='卡号')),
                ('rest_money', models.CharField(max_length=32, verbose_name='剩余金额')),
                ('consume_money', models.CharField(max_length=32, verbose_name='消费金额')),
                ('consume_time', models.DateTimeField(auto_now_add=True, verbose_name='消费时间')),
                ('username', models.CharField(default='', max_length=32, verbose_name='用户名')),
            ],
        ),
    ]
