# Generated by Django 2.0.5 on 2020-04-14 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_cardmoney'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardmoney',
            options={'ordering': ['-consume_time'], 'verbose_name': '消费表', 'verbose_name_plural': '消费表'},
        ),
        migrations.AlterModelTable(
            name='cardmoney',
            table='userconsume',
        ),
    ]
